Repository ANYbotics/grid_map, pull requests merged in 2024-02, with the labels that each got.

#408 Update README.md branches for humble
  README.md
Labels: ros2

#420 Enfore C++17
  grid_map/CMakeLists.txt
  grid_map_cmake_helpers/cmake/grid_map_package.cmake
Labels: ros2

#419 Stop using deprecated CMAKE_COMPILER_IS_GNUCXX
  grid_map_cmake_helpers/cmake/grid_map_package.cmake
  grid_map_demos/CMakeLists.txt
  grid_map_filters/CMakeLists.txt
Labels: ros2

#416 Fix name for Iron
  README.md
Labels: ros2

#404 grid_map_core: Use ament_export_targets and improve eigen linkage
  grid_map_core/CMakeLists.txt
  grid_map_cv/CMakeLists.txt
Labels: ros2

#421 ci(Mergify): Add initial config
  .github/.mergify.yml
Labels: ros2, ci

#418 Add dockerfile for rolling
  .dockerignore
  Dockerfile
Labels: enhancement, ros2, ci

#423 Split PCL deps for dev and runtime
  grid_map_pcl/package.xml
Labels: ros2

#430 Add Github actions for colcon build
  .circleci/config.yml
  .github/workflows/colcon.yaml
Labels: ros2

#424 Use ament_export_targets in grid_map_costmap_2d
  grid_map_costmap_2d/CMakeLists.txt
  grid_map_costmap_2d/test/CMakeLists.txt
Labels: ros2
