Repository ANYbotics/grid_map, pull requests merged in 2024-11, with the labels that each got.

#483 build: switch to use system octomap
  grid_map_octomap/package.xml
Labels: bug, ros2

#481 Fix UB in SpiralIterator::operator++
  grid_map_core/src/iterators/SpiralIterator.cpp
Labels: bug, ros2, backport-iron, backport-humble, backport-jazzy

#491 Add test dependency to on rosbag default plugins
  grid_map_ros/package.xml
Labels: ros2
